name: tellthetruth
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  provider: ^4.0.0
  flutter_offline: ^0.3.0
  intl: ^0.16.1
  permission_handler: ^3.0.2
  firebase_auth: 0.15.4
  cloud_firestore: 0.13.4
  firebase_storage: 3.1.3
  firebase_core: 0.4.4
  flare_flutter: ^2.0.3
  gender_selection: ^1.0.0
  gradient_text: ^1.0.2
  curved_navigation_bar: ^0.3.2
  animations: ^1.0.0+5
  page_transition: ^1.1.5
  lottie: ^0.3.3
  flutter_page_transition: ^0.1.6
  simple_animations: ^1.3.11
  animated_text_kit: 2.0.0
  finite_coverflow: ^1.0.0
  firebase_admob: ^0.9.3+1
  firebase_analytics: ^5.0.11
  animated_widgets: ^1.0.3
  auto_size_text: ^2.1.0
  fab_circular_menu: ^1.0.0
  flutter_open_whatsapp: ^0.1.2
  flutter_slidable: ^0.5.4
  flutter_boom_menu: ^1.0.2
  screenshot: ^0.1.1
  image_gallery_saver: ^1.2.2
  url_launcher: ^5.4.2
  social_share_plugin: ^0.3.1+1



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: FingerPaint
      fonts:
        - asset: fonts/FingerPaint-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/anonymous.png
    - images/boy.png
    - images/empty.flr
    - images/faq.png
    - images/girl.png
    - images/helpline.png
    - images/myGang.png
    - images/myQuestions.png
    - images/no internet.flr
    - images/notAnonymos.png
    - images/options.flr
    - images/people.png
    - images/poll.png
    - images/questionAskedAnonymous.png
    - images/questionNotAskedAnonymous.png
    - images/seen.png
    - images/settingsFAQ.png
    - images/settingsLogout.png
    - images/settingsNotification.png
    - images/settingsSupport.png
    - images/settingsTermsAndConditions.png
    - images/splash.flr
    - images/success-2.flr
    - images/teddy.flr
    - images/walk.flr
    - images/welcome.flr
    - images/whatsapp.png
    - images/settingsPrivacy.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
